### ISSUE TITLE
Performance on ImageNet?

### ISSUE THREAD

**Issue by choasup** [NVlabs/SegFormer#10]
I see that every segmenation config need a pretrained model on Imagenet, so can you provide the performance of B0 - B5 on ImageNet?

**Comment by xieenze** [comment]
Hi,
this is the ImageNet-1K top-1 accuracy. You can refer to it.

![image](https://user-images.githubusercontent.com/20984575/122748647-076b6f80-d2bf-11eb-86b1-e36c9e063a38.png)
