### ISSUE TITLE
did not find the first embeding operation in the codes

### ISSUE THREAD

**Issue by Stephenfang51** [NVlabs/SegFormer#11]
The **3.Method** said that _"Given an image of size H × W × 3, we first divide it into patches of size 4 × 4"_ in the papers, however I did not find the step in your code, could you please point out for me? THanks !

**Comment by xieenze** [comment]
Hi,
Sorry for the late reply.
4x4 patch is a non-overlaping manner for patch embedding, which is used in ViT, DeiT and PVT. We want to present that  it can generate 1/4 size feature map.
But in Section 3.1 we  further introduce an overlapping manner, which has patchsize=7 and stride=4, it can also generate 1/4 size feature map.

[Corresponding code](https://github.com/NVlabs/SegFormer/blob/236eecf091f5006bb1310d1d49cd39ea30f8e720/mmseg/models/backbones/mix_transformer.py#L213).
