### ISSUE TITLE
AssertionError: default process group is not initialized.

### ISSUE THREAD

**Issue by peterlv666** [NVlabs/SegFormer#12]
I follow the readme carefully, it shows as follows:
![image](https://user-images.githubusercontent.com/75125316/122387841-dc70db00-cfa1-11eb-8210-756a8bf61d6c.png)
![image](https://user-images.githubusercontent.com/75125316/122387916-f1e60500-cfa1-11eb-9209-060e577b28e5.png)

**Comment by kotetsu-n** [comment]
I got the same error, but it works with the script for multiple GPU env (I haven't finished the first epoch yet, but it seems working well without errors). 
`./tools/dist_train.sh local_configs/segformer/B1/segformer.b1.512x512.ade.160k.py 1`

**Comment by peterlv666** [comment]
Thanks for your reply. The script also works for me.

**Comment by sharat29ag** [comment]
@kotetsu-n, what you meant by multiple GPU env?
I have one A100; how to solve this error? I tried changing SyncBN to BN, but didn't work.
