### ISSUE TITLE
export segFormer to onnx and then convert to trt error

### ISSUE THREAD

**Issue by AncientRemember** [NVlabs/SegFormer#14]
- the onnx out shape is not determined
- trtexec convert occur GPU out of Memory

**Comment by xieenze** [comment]
Hi, I didn't have experience about ONNX....

**Comment by YazanMurhij995** [comment]
@AncientRemember have you converted the model to trt? how did you build the mmsv library to support trt?

**Comment by yuchenlichuck** [comment]
For robot implementation, we need onnx or openvino version of segformer, but currently, I found that segformer is not to to be converted to those versions, Does anyone can help us to find the reason or share your successful examples, thank you!
