### ISSUE TITLE
support for ASE20k part segmentation

### ISSUE THREAD

**Issue by muhammad-tayyab** [NVlabs/SegFormer#15]
ADE20K dataset contain part segmentation on top of object segmentation. how to achieve part segmentation in segformer

**Comment by xieenze** [comment]
Hi,
I don't know this task of `part segmentation`. But it shouldn't be hard if you have ground-truth. You can follow the `custom_dataset` tutorial in mmsegmentation, to generate your custom dataset, then training and evaluation.
