### ISSUE TITLE
Mapillary Class Remapping

### ISSUE THREAD

**Issue by serser** [NVlabs/SegFormer#16]
Hello, I see that Mapillary uses a remapping to 19 classes, 

https://github.com/NVlabs/SegFormer/blob/3561d14362abe60675755ee00d266308e4e3015e/mmseg/datasets/pipelines/transforms.py#L1025

Does this mean the experiments done in the paper uses 19 classes for all methods on Mapilary?

**Comment by xieenze** [comment]
Yes, it is. 
We re-map the 65 classes in Mapillary to 19 classes in Cityscapes, for pre-training.

**Comment by serser** [comment]
Thanks enze! I see a critical memory outbound when testing in image size (2048, 1024). How much system memory do you use to fit in 2000 images?

**Comment by xieenze** [comment]
I use a 32G V100 for inference, and I haven't meet the memory issue.
I didn't remember the memory. But if your memory isn't enough you can use 'slide test' instead of 'whole test'. The performance is very similar between these two modes.

**Comment by serser** [comment]
Great! I see that slide test loops through all the validation set smoothly. But it seems to fail to compute mIoU due to memory overload again. Is there a way we can survive this?

**Comment by xieenze** [comment]
Oh, I want to confirm two things: 
(1) Which model (from B0 to B5) do you use for testing? 
(2) How large is your GPU memory?

If the sliding test still out of memory, you can smaller the window size,e.g. from`1024x1024` to  `768x768`, this can largely reduce the GPU memory but accuracy slightly drops.

**Comment by serser** [comment]
I haven't tested Segformer on Mapillary yet, but Cityscapes is okay. I am with DeepLabV3+ on Mapillary and it continuously crashes due to memory limit.  My device is 4x 32G V100, 200G physical memory (it is rather due to this mem other than GPU mem).

**Comment by xieenze** [comment]
Oh I see, I have met this problem when eval on Mapillary. 
But I switched to another matching with larger physical memory(about 400G), the problem solved.
MV's image resolution is too large.

**Comment by xieenze** [comment]
If you only want to pretrain, you can eval on cityscapes or discard evalualtion.

**Comment by serser** [comment]
> If you only want to pretrain, you can eval on cityscapes or discard evalualtion.

Nicely done! I'll follow this procedure. I see that mIoU calculation is currently done as a whole instead of incrementally. Due to the very large resolution of MVD, it is indeed unlikely to fit all 2K images in smaller memory. BTW, I see MVD stores the labels in RGB instead of grayscale. Maybe converting to grayscale is a solution? Thanks a million!
