### ISSUE TITLE
Inference speed of the model

### ISSUE THREAD

**Issue by rose-jinyang** [NVlabs/SegFormer#17]
Hello
How are you?
Thanks for contributing to this project.
Which device did u test your models on?

![image](https://user-images.githubusercontent.com/47862419/122716475-e09c4180-d29c-11eb-814d-22c437558a44.png)

You did NOT explain the device specification in the paper.

**Comment by xieenze** [comment]
Hi, we use V100 gpu to test

**Comment by rose-jinyang** [comment]
Thanks for your reply. 
Do u think that the model can yield 20 FPS on a mobile device (ex: snapdragon 662)?

**Comment by xieenze** [comment]
Good question. I didn't try to run it on a mobile device but I believe this is important.
Maybe you need to apply model compression technologies, such as pruning or quantize on the SegFormer-B0.

**Comment by rose-jinyang** [comment]
Got it, thanks
