### ISSUE TITLE
Question on Mapillary pretrain when evaluating on cityscapes(val) dataset

### ISSUE THREAD

**Issue by littleSunlxy** [NVlabs/SegFormer#18]
I met a problem when training on Mapillary and evaluating on cityscapes. The class "wall" miou=0.0. 
Could you please provide the training log of Mapillary pretrain and eval？(prefer Model B2) Thanks a lot!

```
+---------------+-------+-------+
|     Class     |  IoU  |  Acc  |
+---------------+-------+-------+
|      road     | 96.93 | 98.09 |
|    sidewalk   | 76.57 | 90.46 |
|    building   | 89.02 | 95.67 |
|      wall     |  0.0  |  0.0  |
|     fence     | 35.52 | 59.93 |
|      pole     | 52.85 | 63.03 |
| traffic light | 59.63 | 71.81 |
|  traffic sign | 68.11 | 77.09 |
|   vegetation  | 89.89 | 96.67 |
|    terrain    |  26.0 |  26.5 |
|      sky      | 90.97 | 93.58 |
|     person    | 72.78 | 87.27 |
|     rider     | 33.21 |  41.0 |
|      car      | 91.25 | 97.25 |
|     truck     |  61.8 | 64.37 |
|      bus      | 66.93 | 71.56 |
|     train     | 62.85 | 65.31 |
|   motorcycle  | 47.68 | 65.62 |
|    bicycle    | 67.57 | 74.03 |
+---------------+-------+-------+
2021-06-21 16:06:43,150 - mmseg - INFO - Summary:
2021-06-21 16:06:43,150 - mmseg - INFO - 
+-------+-------+-------+
|  aAcc |  mIoU |  mAcc |
+-------+-------+-------+
| 93.66 | 62.61 | 70.49 |
+-------+-------+-------+
```

**Comment by xieenze** [comment]
Hi
Sorry, I didn't try pre-train MV using B2 model, and I didn't have results about eval on cityscapes. 
I only pre-train SegFormer-B5 on MV and finetune on cityscapes. I didn't look at the detail of MV train-> City eval

**Comment by littleSunlxy** [comment]
Oh,I see. I hope to see more details of MV pre-trained ->  City finetune, Do you have the log of SegFormer-B5? Thanks!

**Comment by xieenze** [comment]
No, we didn't organize this part of code and config, so currently we cannot provide it. We consider to public it in the future. (Recently I am busy on other projects)

But it is super easy to pre-train on MV-> finetune on city, if there are some detail make you confuse, you can contact me and I will try to figure it out.
