### ISSUE TITLE
why the b0 results is so bad at  cityscapes, when I train from scratch(don't use pre-trained backbone)

### ISSUE THREAD

**Issue by GitHubChrischen** [NVlabs/SegFormer#19]

**Comment by xieenze** [comment]
(1) Pretrain is essential for semantic segmentation. 
(2) Cityscapes dataset is very small with only 2000 training images.
(3) Other CNN network without pre-train also performs bad.

**Comment by puyiwen** [comment]
> (1) 预训练对于语义分割是必不可少的。 (2) Cityscapes 数据集非常小，只有 2000 张训练图像。 (3) 其他没有预训练的 CNN 网络也表现不佳。

hi,How will I train mit_b4 pre-trained model?
