### ISSUE TITLE
About the efficient attention module

### ISSUE THREAD

**Issue by yihongXU** [NVlabs/SegFormer#21]
Hi,

I would like to ask a question about the efficient attention module, please:
I see that you use a reduction ratio R to descrease the spatial size of input sequences, normally this operation will produce a output sequence of spatial size N/R. But according to your Table.6 it doesn't, the output spatial size is still N. I would like to ask where do you upsample your sequence spatial size from N/R back to N in the attention module after the reduced QKV multiplication? 

Thank you!

**Comment by Chrisding** [comment]
The dimensions of Q K V in our case are N x C, N/R x C and N/R x C. Therefore the dimension of softmax(Q K^T) V is (N x C) x (C x N/R) x (N/R x C) =  (N x N/R) x (N/R x C) = N x C.

**Comment by zhijiejia** [comment]
In paper Section 3.1 Efficient Self-Attention, the last sentence: "In our experiments, we set R to [64, 16, 4, 1] from stage-1 to stage-4" but In table 6, the R from [8, 4, 2, 1] from stage-1 to stage-4, and the code is also [8, 4, 2, 1],  what happend??
