### ISSUE TITLE
license

### ISSUE THREAD

**Issue by AK391** [NVlabs/SegFormer#24]
I was looking to port this to a website but saw the license restriction so decided not to
"3.3 Use Limitation. The Work and any derivative works thereof only may be used or intended for use
non-commercially. Notwithstanding the foregoing, NVIDIA and its affiliates may use the Work and any derivative
works commercially. As used herein, “non-commercially” means for research or evaluation purposes only."
but I see that the authors are ok with it being ported to other websites https://github.com/NVlabs/SegFormer/issues/20
so does what does  evaluation purposes only cover under the license?

**Comment by xieenze** [comment]
I am not very clear about it. I believe non-commercial usage is OK.
To confirm the detail please contact  researchinquiries@nvidia.com.
