### ISSUE TITLE
Results of models trained at 768x768 resolution on Cityscapes

### ISSUE THREAD

**Issue by ydhongHIT** [NVlabs/SegFormer#28]
Is the 80.5mIoU in Table 1 (c) the result obtained at 768x768 resolution for segformer-b2? Or could you provide some results obtained at a crop size of 768x768 during training? Thanks.

**Comment by xieenze** [comment]
Hi, 
yes it is trained on 768x768, and slightly lower than table1(a)'s 81.0 (train on 1024x1024).
