### ISSUE TITLE
Could you publish the Cityscapes-C dataset?

### ISSUE THREAD

**Issue by ydhongHIT** [NVlabs/SegFormer#31]
Can you upload the cityscapes-c dataset? I think it will promote the research of robustness of semantic segmentation.

**Comment by xieenze** [comment]
Hi,
Thanks for interested in our paper.
We may not release cityscapes-C in this project recently.  But we generate cityscapes-C in the same way as this [paper](https://arxiv.org/abs/1908.05005). You can try it.
