### ISSUE TITLE
Pretraining segformer on ImageNet-22K

### ISSUE THREAD

**Issue by htzheng** [NVlabs/SegFormer#32]
The Swin transformer release a large model pretrained on ImageNet-22K for semantic segmentation and achieved a good result. I wonder if you are interested in improving segformer in a similar way? Thanks!

**Comment by xieenze** [comment]
Hi,
Good question. 
Yes, we are planning to pre-train on Imagenet-22k. But actually, it is not easy for us.
Firstly before we do not have enough GPU resources, but recently we will have. 
Then we do not master multi-node training on our GPU clusters, we are still trying to figure it out.
We believe that recently we can pre-train it on Imagenet-22k and release stronger models.

Thanks for the attention!

**Comment by htzheng** [comment]
That would be really great! Thanks for the great work and good luck to you!

**Comment by armored-guitar** [comment]
@xieenze how many epochs have you trained your model on imagenet? cannot find this info

**Comment by pablogiaccaglia** [comment]
Hi, any news on this?
