### ISSUE TITLE
Share Google Colab notebook

### ISSUE THREAD

**Issue by troylane** [NVlabs/SegFormer#33]
Hello, I am wondering if you, or any others here have this implemented in a google colab notebook that you can share.  I am very new to this and would appreciate any assistance to set this up in google colab so that i can fine-tune on a small custom dataset (for school purposes).  Thank you very much

**Comment by xieenze** [comment]
Hi, 
Thanks for interested in our paper!
Indeed Hugging Face is trying to support SegFormer, see [here](https://github.com/NVlabs/SegFormer/issues/20).
When it is finished, they will support training SegFormer in colab. 
Please look forward to that!
