### ISSUE TITLE
Why do not directly use MLP to predict the mask on the concatenated features?

### ISSUE THREAD

**Issue by 3bobo** [NVlabs/SegFormer#35]
Thanks for your work! I have a question. In your decoder, you first use MLP layers to multi-level features to unify the channel dimension and resize them to the same feature size and concatenate them, then you apply an MLP layer again to reduce the channel from 4C to C, and another MLP to predict the segmentation mask. My question is, why you do not directly use the MLP layer on the concatenated features? Have you tested this two-MLPs decoder performance?

**Comment by xieenze** [comment]
Hi
No, I haven't compared these details. I believe the performance should be similar.

**Comment by 3bobo** [comment]
@xieenze , ok, thanks for your reply
