### ISSUE TITLE
Is it possible to use SegFormer for Saliency Object Detection Task?

### ISSUE THREAD

**Issue by vandesa003** [NVlabs/SegFormer#36]
Hi @xieenze , thanks for your great work. I am wondering that whether you have tested ViT based methods for SOD tasks which normally have higher standard for output mask quality. For example, if I need to segment a human portrait, the hair(very thin object) should also be precisely segment out. When I check the demo for SegFormer, I notice that the mask quality especially on the edge is not that good. Do you think this is caused by the labelled data or the network resolution itself?

**Comment by xieenze** [comment]
Hi,
I believe that the edge quality of SegFormer should be high if the annotation quality is high. Please check the cityscapes mask prediction.
I also believe that SegFormer can reach a strong performance on SOD task, welcome you to try it based on SegFormer!

**Comment by vandesa003** [comment]
good to hear, thanks for your information! will have a try!
