### ISSUE TITLE
How to pre-train  on Imagenet?

### ISSUE THREAD

**Issue by prismformore** [NVlabs/SegFormer#39]
Hello,

First, thank you for your excellent work and code! 

May I know how does segformer pre-train on Imagenet? 

Maybe I missed some details in the paper but I didn't find the process of generating the classification token or pooling feature maps as other works do when training for the classification task.

Thank you!

**Comment by xieenze** [comment]
Hi,
The pre-training is similar to DeiT. We do not use additional class token but use avg_pool to get the class token
