### ISSUE TITLE
KeyError: "EncoderDecoder: 'mit_b1 is not in the models registry'"

### ISSUE THREAD

**Issue by 2916850681** [NVlabs/SegFormer#40]
How to solve this problem? I need your hand

**Comment by simonbrislin** [comment]
Yeah. I am having this issue too

**Comment by 2916850681** [comment]
同是天涯沦落人，Please let me know if you have resolved it. Thank you

**Comment by 2916850681** [comment]
> Yeah. I am having this issue too

同是天涯沦落人，Please let me know if you have resolved it. Thank you

**Comment by 2916850681** [comment]
> Yeah. I am having this issue too

Maybe I found the problem, you download the code from Github again, maybe the problem will be solved

**Comment by simonbrislin** [comment]
It doesn't look like there have been any code changes

**Comment by 2916850681** [comment]
you can try it.something is changed in dir mmseg.i do it and the error disappear



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 22, 2021 17:20 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [NVlabs/SegFormer] KeyError: "EncoderDecoder: 'mit_b1 is not in the models registry'" (#40)




 
It doesn't look like there have been any code changes

**Comment by BigDFFF** [comment]
I also had this problem, and then found that it was normal after I installed the timm library and some other libraries. I forgot to follow the steps to install the specified library before I executed the code

**Comment by junzai0215** [comment]
> Yeah. I am having this issue too

how to resolve, thanky

**Comment by Rahul-R-Pai** [comment]
i too am getting the problem, can somebody help
