### ISSUE TITLE
How to change checkpoint saving frequency

### ISSUE THREAD

**Issue by gcilli** [NVlabs/SegFormer#41]
Hi, first of all, thank you for your research and code.

I see that during training, the model is saved every 4000 iterations. Where can I change this spec, such that my model is saved every, lets say, 1000 iterations?

Thank you

**Comment by xieenze** [comment]
Hi
You can change the checkpoints saving frequency at [this config](https://github.com/NVlabs/SegFormer/blob/master/local_configs/_base_/schedules/schedule_160k_adamw.py).

**Comment by gcilli** [comment]
Thank you.
