### ISSUE TITLE
Would it be possible to obtain the code for viewing the ERF of Segformer?

### ISSUE THREAD

**Issue by cyrilzakka** [NVlabs/SegFormer#5]
Hello,

Would it be possible to upload the code for viewing the ERF of Segformer in order to compare it to other network architectures? The images in the paper look very interesting and I'd love to take a close look.

Thanks!

**Comment by xieenze** [comment]
No, we would not plan to open source it because 
(1) it is deeply embedded into existing code, which is not easy to read.
(2) we would like to explore more about ERF on Transformers
