### ISSUE TITLE
Computing the effective receptive fields (figure 6 of the paper)

### ISSUE THREAD

**Issue by ArthurZucker** [NVlabs/SegFormer#64]
Thanks for the great work!
I would like to know if you could share the code to compute the effective receptive fields and visualize them.
Best,

**Comment by GrimreaperZ-creator** [comment]
me too

**Comment by ArthurZucker** [comment]
I guess you just have to compute the derivative of the output feature map with respect to the input image. You can use callbacks and `autograd.grad`. It's probably why they did not provide the code

**Comment by ArthurZucker** [comment]
I guess you just have to compute the derivative of the output feature map with respect to the input image. You can use callbacks and `autograd.grad`. It's probably why they did not provide the code

**Comment by GrimreaperZ-creator** [comment]
Thank you for your answer
