### ISSUE TITLE
Pre-train Code or implementation details

### ISSUE THREAD

**Issue by yi94code** [NVlabs/SegFormer#67]
Hi,

First, thank you for your excellent work and code!

But I didn't find the details about how to pre-train mit on the Imagenet-1K dataset. Could you please release the code for pre-training the encoder on the Imagenet-1K dataset?

Thank you!

**Comment by xieenze** [comment]
you can refer to PVTv2 (https://github.com/whai362/PVT/tree/v2/classification/configs/pvt_v2)
MiT is almost same as PVTv2.
