### ISSUE TITLE
No module named 'mmseg'

### ISSUE THREAD

**Issue by ooodragon94** [NVlabs/SegFormer#68]
hi thanks for your great repo

I have no idea why but it seems to import mmseg not from local module but from installed one
and it keeps shows me this error

No module named 'mmseg'

When I run pycharm as debugging mode, than it works all fine... only when I try to run it with terminal or run mode...

any help will be very appreciated

**Comment by TrinhThiBaoAnh** [comment]
@ooodragon94  : pip3  install mmsegmentation . That works for me

**Comment by ooodragon94** [comment]
@TrinhThiBaoAnh Thanks for your reply
It seems like the problem was within pycharm where debugging interpreter and running interpreter was different.
Wasn't able to solve it though...

Closing this issue.

**Comment by LinusKaiser** [comment]
I'm having the same issue. When I do `pip3 install mmsegmentation` and execute again it tells me that "*there is no module named mmcv*". When I then also do `pip3 install mmcv`and execute again it gives me the following error message:

```python
╰─ python3 ml_models/SegFormer/SegFormer/demo/image_demo.py
Traceback (most recent call last):
  File "/Users/suntim/Documents/Work/Instagram/ml_models/SegFormer/SegFormer/demo/image_demo.py", line 3, in <module>
    from mmseg.apis import inference_segmentor, init_segmentor, show_result_pyplot
ImportError: cannot import name 'inference_segmentor' from 'mmseg.apis' (/Users/suntim/opt/miniconda3/envs/python3.10.4/lib/python3.10/site-packages/mmseg/apis/__init__.py)
```

**Comment by whut-zhangwx** [comment]
I encountered the same isssue, and I solved it by reinstall the mmsegmentation

```shell
...\mmsegmentation>pip install -v -e . 
```

**Comment by Mura0014** [comment]
Could you tell me mmcv's version and mmseg'version??
