### ISSUE TITLE
train error mit_b1.pth is not a checkpoint file

### ISSUE THREAD

**Issue by peterlv666** [NVlabs/SegFormer#7]
It's a great honor for me to study your reserch, when i download the pretrained model into pretrained directory . It shows as follows, hope you can give me some advice. Thanks for your time and kindness.
![image](https://user-images.githubusercontent.com/75125316/122185775-f5a15b00-cebf-11eb-8bbf-368e9a77ddb0.png)

**Comment by AncientRemember** [comment]
maybe youre checkpoint is damaged while transfer, i have download the pretrained checkpoint and loadchekpoints correct

**Comment by peterlv666** [comment]
@AncientRemember Did you download the ADE20K dataset before training? And if you did,  can you tell me how to download the ADE20K dataset. Thanks for your time.

**Comment by xieenze** [comment]
> @AncientRemember Did you download the ADE20K dataset before training? And if you did, can you tell me how to download the ADE20K dataset. Thanks for your time.

Please refer to the docs of mmsegmentation about how to download ADE20K dataset. Thanks

**Comment by mamba824824** [comment]
> It's a great honor for me to study your reserch, when i download the pretrained model into pretrained directory . It shows as follows, hope you can give me some advice. Thanks for your time and kindness.
> ![image](https://user-images.githubusercontent.com/75125316/122185775-f5a15b00-cebf-11eb-8bbf-368e9a77ddb0.png)

hello. Did you solve the question.
I met the same question, could you tell me how to solve that. Thanks.

**Comment by junzai0215** [comment]
> > It's a great honor for me to study your reserch, when i download the pretrained model into pretrained directory . It shows as follows, hope you can give me some advice. Thanks for your time and kindness.
> > ![image](https://user-images.githubusercontent.com/75125316/122185775-f5a15b00-cebf-11eb-8bbf-368e9a77ddb0.png)
> 
> Hello. Did you solve the problem. I met the same error, could you tell me how to solve that. Where could i get the pth file. Thanks.

Did you solve the problem, can you tell me, thanks
