### ISSUE TITLE
training error: unrecognized arguments

### ISSUE THREAD

**Issue by peterlv666** [NVlabs/SegFormer#9]
When i use your script command 'python tools/train.py local_configs/segformer/B1/segformer.b1.512x512.ade.160k.py 
', it shows unrecognized arguments as follows. Can you tell me how to solve it ?
![image](https://user-images.githubusercontent.com/75125316/122220316-cc45f680-cee2-11eb-8b33-64c5765b782c.png)

**Comment by xieenze** [comment]
I can successfully run this script on my local machine. 
Did you install this project follow the readme?

**Comment by peterlv666** [comment]
@xieenze yeah, i follow the MMsegmentation and can run the image_demo.py.   Is there any other operation to perform?
